### ISSUE TITLE
use File::Spec->catfile/catdir

### ISSUE THREAD

**Issue by nicolasfranck** [dagolden/Path-Iterator-Rule#24]
Path::Iterator::Rule hardcodes forward slashes in its paths.
Is this intended? Shouldn't it use something like File::Spec->catfile?
It generates invalid paths in Windows (although newer versions
of Windows do support forward slashes).

**Comment by xdg** [comment]
It's intentional, but should be documented.

File::Spec is slow.  All of its operations call 'canonpath' on the argument(s).

The PIR paths generated are valid for use on any supported Windows, at least for use within Perl, regardless of slash direction.  If someone really need canonical slashes, they can wash PIR's output through File::Spec themselves, so I don't want to impose a canonicalization burden on everyone including those who might not need it.
